name: flutter_application_2023
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
 
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  
  country_picker: ^2.0.19
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.2
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14
  shared_preferences: ^2.0.18
  provider:
  pinput: ^2.2.31
  image_picker:
  google_fonts: ^4.0.3
  google_nav_bar: ^5.0.6
  get: ^4.6.5
  intl: ^0.18.0
  simple_gradient_text: ^1.2.4
  camera: ^0.10.3+2
  path_provider: ^2.0.15
  carousel_slider: ^4.2.1
  razorpay_flutter: ^1.3.0
  http: ^0.13.5
  toast: ^0.2.9
  google_sign_in: ^5.2.1
  cached_network_image: ^3.2.3
  gallery_saver: ^2.3.2
  firebase_messaging: ^14.3.0
  flutter_notification_channel: ^2.0.0
  emoji_picker_flutter: ^1.5.1
  flutter_svg:
  uuid: ^3.0.7
  dio: ^5.2.1+1
  flutter_badged: ^2.0.2
  fluttertoast: ^8.0.8
  like_button: ^2.0.4
  font_awesome_flutter: ^10.1.0
  lottie:
  flutterfire_ui: ^0.4.1
  firebase_analytics: ^10.2.1
  flutter_mentions: ^2.0.1
  linkfy_text: ^1.1.5
  story_view: ^0.14.0
  random_string:
  photo_view:
  flutter_local_notifications:
  cloud_functions:
  collection: ^1.16.0
  faker: ^2.0.0
  jiffy: ^5.0.0
  logger: ^1.1.0
  meta: ^1.7.0
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  percent_indicator: 
  bubble: ^1.2.1
  package_info_plus: ^4.0.1
  badges:  ^2.0.3
  screenshot: ^2.1.0
  image_gallery_saver: ^2.0.2
  permission_handler: 
  full_screen_image: ^2.0.0
  rating_dialog: ^2.0.3
  file_picker: ^5.2.5
  image_cropper: ^3.0.1
  flutter_colorpicker: ^1.0.3
  flutter_spinkit:
  agora_uikit: ^1.0.2
  audioplayers: ^1.0.1
  # cached_video_player:
  enough_giphy_flutter: ^0.3.0
  agora_rtc_engine:
  connectivity_plus:
  bottom_navy_bar:


  shimmer_animation: ^2.1.0+1
  country_state_city_picker: ^1.2.8
  flutter_easyloading: ^3.0.5
  # date_time_picker: ^2.0.0
  date_time_format: ^2.0.1
  firebase_ui_auth: ^1.1.12
  flutter_slidable: ^2.0.0

  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  flutter_polyline_points: ^1.0.0
  url_launcher: ^6.1.11
  flutter_rating_bar: ^4.0.1
  rating_summary: ^1.0.2+1
  custom_rating_bar: ^2.0.5

  freezed: ^1.1.0
  freezed_annotation: ^1.1.0

 

  pip_view: ^0.9.7


  







  
  # flutter_icons:
  #   git:
  #     url: https://github.com/adarsh-technocrat/flutter-icons
  # flutter_facebook_auth:
  # animations: ^2.0.7
  # loading_overlay: ^0.3.0
  # # flutter_geocoder:
  # currency_picker: ^2.0.3
  # geolocator: ^9.0.2
  # connectivity: ^3.0.6
  # dropdown_search: ^0.6.3
  # flutter_launcher_icons: ^0.9.1

  # flutter_rating_bar:
  # animated_text_kit: ^4.1.1
  # path:
  # connectivity: ^3.0.4



  




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lang/ar.json
    - assets/lang/en.json
    - assets/images/
    - assets/lottie/
    - assets/
    - assets/images/cr1.jpg
    - assets/images/c2.png
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
