// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABci8JgVHaVRkt_FMmhhkGMbPk1okSio4',
    appId: '1:168217810649:web:0eb898ae6a6a2c593950c8',
    messagingSenderId: '168217810649',
    projectId: 'myapp--backend',
    authDomain: 'myapp--backend.firebaseapp.com',
    storageBucket: 'myapp--backend.appspot.com',
    measurementId: 'G-RQD3CBWY1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpMjmlxR_5cRgf4uhOzvYKaVyESMVI9-g',
    appId: '1:168217810649:android:e4047536525d77d83950c8',
    messagingSenderId: '168217810649',
    projectId: 'myapp--backend',
    storageBucket: 'myapp--backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiiALaiqTqJBOuzdC6Z5l40p9uhlN7BcU',
    appId: '1:168217810649:ios:39ee763c1de8dc423950c8',
    messagingSenderId: '168217810649',
    projectId: 'myapp--backend',
    storageBucket: 'myapp--backend.appspot.com',
    androidClientId: '168217810649-3hb90trlon3bnqsrirn98q91b938qgpv.apps.googleusercontent.com',
    iosClientId: '168217810649-rlitn46cj4kdn57fctlcc48ldkhqqcmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiiALaiqTqJBOuzdC6Z5l40p9uhlN7BcU',
    appId: '1:168217810649:ios:39ee763c1de8dc423950c8',
    messagingSenderId: '168217810649',
    projectId: 'myapp--backend',
    storageBucket: 'myapp--backend.appspot.com',
    androidClientId: '168217810649-3hb90trlon3bnqsrirn98q91b938qgpv.apps.googleusercontent.com',
    iosClientId: '168217810649-rlitn46cj4kdn57fctlcc48ldkhqqcmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2023',
  );
}
